import dims from "./image-dimensions.json";

export interface ImageDimensions {
  width: number;
  height: number;
}

/**
 * Real pixel dimensions per cover image, generated by
 * scripts/normalize-blog-covers.mjs (which also guarantees every cover is
 * >=1200px wide for Google Discover). Lookup returns undefined for unknown
 * paths so callers can omit width/height rather than guess.
 */
export function getCoverDimensions(coverPath: string): ImageDimensions | undefined {
  const entry = (dims as Record<string, ImageDimensions | null>)[coverPath];
  return entry ?? undefined;
}
