// Lightweight tool metadata for CLIENT components.
// Do NOT import the full tools registry here — it includes FAQ/content blobs
// that bloat the browser bundle. Server pages should keep using @/config/tools.

import {
    FaImage,
    FaMagic,
    FaRocket,
    FaHeading,
    FaAlignLeft,
    FaTags,
    FaSearch,
    FaLightbulb,
    FaChartLine,
    FaCalendarAlt,
    FaDollarSign,
    FaChartBar,
    FaBalanceScale,
    FaUser,
    FaHashtag,
    FaMicrophone,
    FaIdCard,
    FaListUl,
    FaTrophy,
    FaUsers,
    FaDownload,
    FaClock,
    FaVideo,
    FaPaintBrush,
    FaCompass,
    FaHandshake,
    FaCoins,
    FaFileInvoiceDollar,
} from "react-icons/fa";
import type { IconType } from "react-icons";

export interface ToolMeta {
    slug: string;
    name: string;
    description: string;
    shortDescription: string;
    category: string;
    icon: IconType;
    isAI: boolean;
    isFeatured: boolean;
}

export const toolMeta: ToolMeta[] = [
    {
        slug: "youtube-thumbnail-downloader",
        name: "YouTube Thumbnail Downloader (HD & 4K)",
        description: "Download high-quality thumbnails from any YouTube video. Get all resolutions including HD and SD versions instantly. No signup required.",
        shortDescription: "Download thumbnails from any YouTube video",
        category: "thumbnail-media",
        icon: FaImage,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-thumbnail-generator",
        name: "YouTube Thumbnail Text Generator",
        description: "Generate catchy thumbnail text ideas using AI. Get punchy, clickable text suggestions that grab attention and boost your CTR.",
        shortDescription: "AI-powered thumbnail text ideas",
        category: "thumbnail-media",
        icon: FaMagic,
        isAI: true,
        isFeatured: true,
    },
    {
        slug: "youtube-ai-thumbnail-generator",
        name: "AI Thumbnail Image Generator",
        description: "Generate stunning thumbnail images with AI. Just describe what you want and get a unique, professional thumbnail in seconds optimized for YouTube.",
        shortDescription: "Generate thumbnail images with AI",
        category: "thumbnail-media",
        icon: FaImage,
        isAI: true,
        isFeatured: true,
    },
    {
        slug: "youtube-ai-thumbnail-prompt",
        name: "AI Thumbnail Prompt Generator",
        description: "Generate professional AI prompts for stunning YouTube thumbnails. Works with DALL-E, Midjourney, Stable Diffusion, and any AI image generator.",
        shortDescription: "Create perfect AI image prompts",
        category: "thumbnail-media",
        icon: FaRocket,
        isAI: true,
        isFeatured: true,
    },
    {
        slug: "youtube-title-generator",
        name: "YouTube Title Generator",
        description: "Generate SEO-optimized, clickable YouTube titles using AI. Choose from different tones, emotional hooks, and languages to boost your CTR.",
        shortDescription: "AI-generated SEO titles",
        category: "seo-metadata",
        icon: FaHeading,
        isAI: true,
        isFeatured: true,
    },
    {
        slug: "youtube-description-generator",
        name: "YouTube SEO Description Generator",
        description: "Create engaging, high-ranking video descriptions with AI. Includes hooks, structured bullet points, CTAs, and optimized hashtags.",
        shortDescription: "AI-powered video descriptions",
        category: "seo-metadata",
        icon: FaAlignLeft,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-tag-generator",
        name: "YouTube Tag Generator",
        description: "Generate SEO-optimized, trending tags that help your videos rank. Get a mix of primary, search, and long-tail keywords in seconds.",
        shortDescription: "Generate SEO tags for videos",
        category: "seo-metadata",
        icon: FaTags,
        isAI: true,
        isFeatured: true,
    },
    {
        slug: "youtube-tag-extractor",
        name: "YouTube Tag Extractor",
        description: "Extract hidden meta tags from any YouTube video URL. See exactly what keywords successful channels are using to rank and get suggested.",
        shortDescription: "Extract tags from any video",
        category: "seo-metadata",
        icon: FaSearch,
        isAI: false,
        isFeatured: false,
    },
    {
        slug: "youtube-video-ideas-generator",
        name: "Strategic Video Ideas Generator",
        description: "Get proven video concepts tailored to your channel size and growth goals. Includes titles, thumbnails, and difficulty ratings for maximum impact.",
        shortDescription: "AI video ideas for your niche",
        category: "channel-growth",
        icon: FaLightbulb,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-trend-helper",
        name: "YouTube Trend & Topic Helper",
        description: "Discover trending topics in your region and get AI-powered video ideas tailored to your niche using real-time YouTube data and predictive analytics.",
        shortDescription: "Find trending topics & viral ideas",
        category: "channel-growth",
        icon: FaChartLine,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-content-calendar-generator",
        name: "AI Content Calendar Generator",
        description: "Plan your YouTube success with our AI Content Calendar Generator. Create a consistent, strategic content schedule with video ideas tailored to your niche.",
        shortDescription: "Plan your content schedule",
        category: "channel-growth",
        icon: FaCalendarAlt,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-earnings-calculator",
        name: "YouTube Earnings Calculator",
        description: "Estimate YouTube AdSense revenue from monthly views and RPM. Compare country CPM ranges, model high-intent niches, and plan monthly/yearly creator income.",
        shortDescription: "Estimate AdSense revenue by views & RPM",
        category: "analytics-earnings",
        icon: FaDollarSign,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-engagement-rate-calculator",
        name: "Engagement Rate Calculator",
        description: "Calculate your YouTube video's engagement rate. Measure how actively your audience interacts with your content.",
        shortDescription: "Measure video engagement",
        category: "analytics-earnings",
        icon: FaChartBar,
        isAI: false,
        isFeatured: false,
    },
    {
        slug: "youtube-title-ab-tester",
        name: "Title A/B Score Checker",
        description: "Compare two titles and get AI scoring for click-through potential, clarity, and emotional appeal to maximize your video reach.",
        shortDescription: "Compare title effectiveness",
        category: "analytics-earnings",
        icon: FaBalanceScale,
        isAI: true,
        isFeatured: true,
    },
    {
        slug: "youtube-channel-name-generator",
        name: "YouTube Channel Name Generator",
        description: "Generate unique, memorable YouTube channel name ideas. Find the perfect name for your brand with our AI-powered naming engine.",
        shortDescription: "Find your perfect channel name",
        category: "utility-fun",
        icon: FaUser,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-hashtag-generator",
        name: "YouTube Hashtag Generator",
        description: "Generate relevant hashtags for your YouTube videos. Get broad and specific hashtag suggestions tailored to the 2026 discovery algorithm.",
        shortDescription: "Generate video hashtags",
        category: "utility-fun",
        icon: FaHashtag,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-intro-script-generator",
        name: "Intro Script Generator",
        description: "Create engaging video intro scripts with AI. Hook your viewers in the first 15-30 seconds with results-driven psychology.",
        shortDescription: "Write compelling intros",
        category: "utility-fun",
        icon: FaMicrophone,
        isAI: true,
        isFeatured: false,
    },
    {
        slug: "youtube-channel-id-finder",
        name: "YouTube Channel ID Finder",
        description: "Find the unique Channel ID (UC...) and User ID for any YouTube channel. Essential for API integrations and advanced research in 2026.",
        shortDescription: "Find any YouTube Channel ID",
        category: "utility-fun",
        icon: FaIdCard,
        isAI: false,
        isFeatured: false,
    },
    {
        slug: "youtube-playlist-length-calculator",
        name: "YouTube Playlist Length Calculator",
        description: "Calculate the total length of any YouTube playlist. See how long it takes to watch at specific speeds (1.25x, 1.5x, 2x).",
        shortDescription: "Calculate playlist duration",
        category: "utility-fun",
        icon: FaListUl,
        isAI: false,
        isFeatured: false,
    },
    {
        slug: "youtube-comment-picker",
        name: "YouTube Comment Picker",
        description: "Pick a random winner from loaded public YouTube comments with duplicate and keyword filters.",
        shortDescription: "Pick random comment winner",
        category: "utility-fun",
        icon: FaTrophy,
        isAI: false,
        isFeatured: false,
    },
    {
        slug: "youtube-channel-audit",
        name: "YouTube Channel Audit Checklist",
        description: "Review your creator workflow with an honest self-assessment checklist and a short list of practical next improvements.",
        shortDescription: "Review your creator workflow checklist",
        category: "channel-growth",
        icon: FaChartBar,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-subscriber-count-checker",
        name: "YouTube Subscriber Count Checker",
        description: "Check public subscriber, video, and view counts for a YouTube channel using the official YouTube Data API.",
        shortDescription: "Check public YouTube channel statistics",
        category: "analytics-earnings",
        icon: FaUsers,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-video-download-options",
        name: "YouTube Video Download Options Guide",
        description: "Choose your goal and get a policy-safe YouTube option without extracting, caching, or storing video files.",
        shortDescription: "Find official YouTube download and sharing options",
        category: "utility-fun",
        icon: FaDownload,
        isAI: false,
        isFeatured: false,
    },
    {
        slug: "youtube-timestamp-generator",
        name: "YouTube Timestamp Generator",
        description: "Turn a video outline into description-ready YouTube timestamps and chapter labels locally in your browser.",
        shortDescription: "Format YouTube chapters from an outline",
        category: "seo-metadata",
        icon: FaClock,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-shorts-script-planner",
        name: "YouTube Shorts Script and Shot Planner",
        description: "Build a YouTube Shorts script, shot timeline, and recording checklist without uploading your footage.",
        shortDescription: "Plan a Shorts script and shot timeline",
        category: "channel-growth",
        icon: FaVideo,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-banner-logo-maker",
        name: "YouTube Banner and Logo Maker",
        description: "Create a simple YouTube banner and matching logo locally, with a safe-area preview for important text.",
        shortDescription: "Create local banner and logo PNG files",
        category: "thumbnail-media",
        icon: FaPaintBrush,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-niche-finder-quiz",
        name: "YouTube Niche Finder Quiz",
        description: "Find a practical YouTube niche direction based on your strengths and preferred video format.",
        shortDescription: "Find niche ideas that fit your strengths",
        category: "channel-growth",
        icon: FaCompass,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-sponsorship-calculator",
        name: "YouTube Sponsorship Rate Calculator",
        description: "Estimate how much money you should charge brands for sponsored integrations, shoutouts, and dedicated YouTube videos based on views, niche CPM, and deliverables.",
        shortDescription: "Calculate how much to charge for YouTube brand deals and sponsorships",
        category: "analytics-earnings",
        icon: FaHandshake,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-channel-valuation-calculator",
        name: "YouTube Channel Valuation Calculator",
        description: "Calculate the estimated market value and acquisition price of a YouTube channel based on monthly net profit, revenue diversification, and creator industry multiples.",
        shortDescription: "Estimate the market value and net worth of any YouTube channel",
        category: "analytics-earnings",
        icon: FaCoins,
        isAI: false,
        isFeatured: true,
    },
    {
        slug: "youtube-tax-deduction-calculator",
        name: "YouTube Creator Tax & Write-Off Calculator",
        description: "Plan creator business expenses and explore a possible tax reduction using an adjustable rate assumption.",
        shortDescription: "Plan creator expenses and compare illustrative tax reduction scenarios",
        category: "analytics-earnings",
        icon: FaFileInvoiceDollar,
        isAI: false,
        isFeatured: false,
    },
];

export function getToolMetaBySlug(slug: string): ToolMeta | undefined {
    return toolMeta.find((t) => t.slug === slug);
}
